### ISSUE TITLE
EventHandler for Dynap-se (monitor neurons) broken with current cAER/Visualizer

### ISSUE THREAD

**Issue by federicohyo** [inilabs/caer#100]
By default in the older version of cAER by clicking on any neuron on the visualizer the neurons were directed in the analog output monitor.
Something has changed in the newer cAER version and now the neurons cannot be probed anymore. The EventHandler need to be fixed as it was previously, as that was a very useful feature.

**Comment by llongi** [comment]
The EventHandler for a visualizer, being now a generic system, is set to NONE by default. To use the spike monitoring event handler, this has to be set to "Spikes" instead. The default dynapse-config.xml has been updated to do this.
