### ISSUE TITLE
libcaer / caer initialization fails on dynapse

### ISSUE THREAD

**Issue by federicohyo** [inilabs/caer#106]
New initialization is not carried correctly, same board does not initialize fine with current master libcaer / caer. (Some cores are dead at startup). However, the same dynapse board initialize fine with caer 0.9.13 and libcaer 2.1.5. This suggest that something must have changed in the way the Dynapse board is initialized via libcaer  or in dynapse_common.h. Startup procedure is critical for analog hardware and must be tested carefully.

**Comment by llongi** [comment]
Fixed in https://github.com/inilabs/libcaer/commit/9dd0d62079ac1c4e62c5b7f8ed626914589ef123.
