### ISSUE TITLE
master cAER segmentation fault on shutdown

### ISSUE THREAD

**Issue by federicohyo** [inilabs/caer#107]
current version of cAER gives segmentation fault on closing when adding or removing modules during run times. This can be observed easily when multiple modules are running, try to add or remove a module using the GUI bu stopping and re-launching the mainloop, it will segfault during shutdown.

**Comment by llongi** [comment]
Fixed in https://github.com/inilabs/caer/commit/6ae0ab55218e072fdd86db29886ecc7c3000c56e.
