### ISSUE TITLE
FileInput module broken:

### ISSUE THREAD

**Issue by federicohyo** [inilabs/caer#11]
Recording and playing files is broken with the error 10-FileInput: Failed to parse event packets.

./caer-bin 
2016-06-10 15:50:23 (TZ+0200): NOTICE: Logger: Initialization successful with log-level 5.
2016-06-10 15:50:23 (TZ+0200): NOTICE: Config Server: Ready and listening on 127.0.0.1:4040.
2016-06-10 15:50:23 (TZ+0200): ERROR: 10-FileInput: Failed to parse event packets.
Total events/second:          0 - Valid events/second:          02016-06-10 15:50:25 (TZ+0200): ERROR: 10-FileInput: Failed to parse event packets.

**Comment by llongi** [comment]
No clue. Post your caer-config.xml please.

**Comment by federicohyo** [comment]
just updated.. recording was done yesterday:

Federicos-MacBook-Air:caer_git federicocorradi$ ./caer-bin 
2016-06-11 12:10:37 (TZ+0200): NOTICE: Logger: Initialization successful with log-level 5.
2016-06-11 12:10:37 (TZ+0200): NOTICE: Mainloop: LASER SCANNER ENABLED
2016-06-11 12:10:37 (TZ+0200): NOTICE: Config Server: Ready and listening on 127.0.0.1:4040.
2016-06-11 12:10:37 (TZ+0200): ERROR: 10-FileInput: No compliant Format header found. Invalid file.
2016-06-11 12:10:37 (TZ+0200): ERROR: 10-FileInput: Failed to parse header.
2016-06-11 12:10:37 (TZ+0200): NOTICE: PoseCalibration CXX loadCalibrationFile(): Camera matrix and distorsion coefficients succesfully loaded
Total events/second:          0 - Valid events/second:          02016-06-11 12:10:38 (TZ+0200): NOTICE: PoseCalibration CXX loadCalibrationFile(): Camera matrix and distorsion coefficients succesfully loaded
Total events/second:          0 - Valid events/second:          02016-06-11 12:10:40 (TZ+0200): ERROR: 10-FileInput: No compliant Format header found. Invalid file.
2016-06-11 12:10:40 (TZ+0200): ERROR: 10-FileInput: Failed to parse header.


<sshs version="1.0">
    <node name="" path="/">
        <node name="1" path="/1/">
            <node name="1-DAVISFX3" path="/1/1-DAVISFX3/">
                <attr key="autoRestart" type="bool">true</attr>
                <attr key="busNumber" type="short">0</attr>
                <attr key="devAddress" type="short">0</attr>
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="serialNumber" type="string"></attr>
                <node name="DAVIS346B" path="/1/1-DAVISFX3/DAVIS346B/">
                    <node name="aps" path="/1/1-DAVISFX3/DAVIS346B/aps/">
                        <attr key="ADCTestMode" type="bool">false</attr>
                        <attr key="ColumnSettle" type="short">60</attr>
                        <attr key="EndColumn0" type="short">345</attr>
                        <attr key="EndColumn1" type="short">346</attr>
                        <attr key="EndColumn2" type="short">346</attr>
                        <attr key="EndColumn3" type="short">346</attr>
                        <attr key="EndRow0" type="short">259</attr>
                        <attr key="EndRow1" type="short">260</attr>
                        <attr key="EndRow2" type="short">260</attr>
                        <attr key="EndRow3" type="short">260</attr>
                        <attr key="Exposure" type="int">7000</attr>
                        <attr key="FrameDelay" type="int">1000</attr>
                        <attr key="GlobalShutter" type="bool">true</attr>
                        <attr key="NullSettle" type="short">6</attr>
                        <attr key="RampReset" type="short">20</attr>
                        <attr key="RampShortReset" type="bool">false</attr>
                        <attr key="ResetRead" type="bool">true</attr>
                        <attr key="ResetSettle" type="short">20</attr>
                        <attr key="RowSettle" type="short">20</attr>
                        <attr key="Run" type="bool">true</attr>
                        <attr key="SampleEnable" type="bool">true</attr>
                        <attr key="SampleSettle" type="short">60</attr>
                        <attr key="StartColumn0" type="short">0</attr>
                        <attr key="StartColumn1" type="short">346</attr>
                        <attr key="StartColumn2" type="short">346</attr>
                        <attr key="StartColumn3" type="short">346</attr>
                        <attr key="StartRow0" type="short">0</attr>
                        <attr key="StartRow1" type="short">260</attr>
                        <attr key="StartRow2" type="short">260</attr>
                        <attr key="StartRow3" type="short">260</attr>
                        <attr key="TakeSnapShot" type="bool">false</attr>
                        <attr key="UseInternalADC" type="bool">true</attr>
                        <attr key="WaitOnTransferStall" type="bool">true</attr>
                    </node>
                    <node name="bias" path="/1/1-DAVISFX3/DAVIS346B/bias/">
                        <node name="AEPdBn" path="/1/1-DAVISFX3/DAVIS346B/bias/AEPdBn/">
                            <attr key="coarseValue" type="byte">6</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">91</attr>
                            <attr key="sex" type="string">N</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="AEPuXBp" path="/1/1-DAVISFX3/DAVIS346B/bias/AEPuXBp/">
                            <attr key="coarseValue" type="byte">4</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">80</attr>
                            <attr key="sex" type="string">P</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="AEPuYBp" path="/1/1-DAVISFX3/DAVIS346B/bias/AEPuYBp/">
                            <attr key="coarseValue" type="byte">7</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">152</attr>
                            <attr key="sex" type="string">P</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="AdcCompBp" path="/1/1-DAVISFX3/DAVIS346B/bias/AdcCompBp/">
                            <attr key="coarseValue" type="byte">5</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">20</attr>
                            <attr key="sex" type="string">P</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="AdcRefHigh" path="/1/1-DAVISFX3/DAVIS346B/bias/AdcRefHigh/">
                            <attr key="currentValue" type="byte">7</attr>
                            <attr key="voltageValue" type="byte">30</attr>
                        </node>
                        <node name="AdcRefLow" path="/1/1-DAVISFX3/DAVIS346B/bias/AdcRefLow/">
                            <attr key="currentValue" type="byte">7</attr>
                            <attr key="voltageValue" type="byte">1</attr>
                        </node>
                        <node name="AdcTestVoltage" path="/1/1-DAVISFX3/DAVIS346B/bias/AdcTestVoltage/">
                            <attr key="currentValue" type="byte">7</attr>
                            <attr key="voltageValue" type="byte">21</attr>
                        </node>
                        <node name="ApsCas" path="/1/1-DAVISFX3/DAVIS346B/bias/ApsCas/">
                            <attr key="currentValue" type="byte">6</attr>
                            <attr key="voltageValue" type="byte">21</attr>
                        </node>
                        <node name="ApsOverflowLevel" path="/1/1-DAVISFX3/DAVIS346B/bias/ApsOverflowLevel/">
                            <attr key="currentValue" type="byte">6</attr>
                            <attr key="voltageValue" type="byte">27</attr>
                        </node>
                        <node name="ApsROSFBn" path="/1/1-DAVISFX3/DAVIS346B/bias/ApsROSFBn/">
                            <attr key="coarseValue" type="byte">6</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">219</attr>
                            <attr key="sex" type="string">N</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="BiasBuffer" path="/1/1-DAVISFX3/DAVIS346B/bias/BiasBuffer/">
                            <attr key="coarseValue" type="byte">7</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">255</attr>
                            <attr key="sex" type="string">N</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="ColSelLowBn" path="/1/1-DAVISFX3/DAVIS346B/bias/ColSelLowBn/">
                            <attr key="coarseValue" type="byte">0</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">1</attr>
                            <attr key="sex" type="string">N</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="DACBufBp" path="/1/1-DAVISFX3/DAVIS346B/bias/DACBufBp/">
                            <attr key="coarseValue" type="byte">6</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">60</attr>
                            <attr key="sex" type="string">P</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="DiffBn" path="/1/1-DAVISFX3/DAVIS346B/bias/DiffBn/">
                            <attr key="coarseValue" type="byte">4</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">50</attr>
                            <attr key="sex" type="string">N</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="IFRefrBn" path="/1/1-DAVISFX3/DAVIS346B/bias/IFRefrBn/">
                            <attr key="coarseValue" type="byte">5</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">255</attr>
                            <attr key="sex" type="string">N</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="IFThrBn" path="/1/1-DAVISFX3/DAVIS346B/bias/IFThrBn/">
                            <attr key="coarseValue" type="byte">5</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">255</attr>
                            <attr key="sex" type="string">N</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="LcolTimeoutBn" path="/1/1-DAVISFX3/DAVIS346B/bias/LcolTimeoutBn/">
                            <attr key="coarseValue" type="byte">5</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">49</attr>
                            <attr key="sex" type="string">N</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="LocalBufBn" path="/1/1-DAVISFX3/DAVIS346B/bias/LocalBufBn/">
                            <attr key="coarseValue" type="byte">5</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">164</attr>
                            <attr key="sex" type="string">N</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="OffBn" path="/1/1-DAVISFX3/DAVIS346B/bias/OffBn/">
                            <attr key="coarseValue" type="byte">3</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">1</attr>
                            <attr key="sex" type="string">N</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="OnBn" path="/1/1-DAVISFX3/DAVIS346B/bias/OnBn/">
                            <attr key="coarseValue" type="byte">5</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">255</attr>
                            <attr key="sex" type="string">N</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="PadFollBn" path="/1/1-DAVISFX3/DAVIS346B/bias/PadFollBn/">
                            <attr key="coarseValue" type="byte">7</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">false</attr>
                            <attr key="fineValue" type="short">215</attr>
                            <attr key="sex" type="string">N</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="PixInvBn" path="/1/1-DAVISFX3/DAVIS346B/bias/PixInvBn/">
                            <attr key="coarseValue" type="byte">7</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">129</attr>
                            <attr key="sex" type="string">N</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="PrBp" path="/1/1-DAVISFX3/DAVIS346B/bias/PrBp/">
                            <attr key="coarseValue" type="byte">2</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">255</attr>
                            <attr key="sex" type="string">P</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="PrSFBp" path="/1/1-DAVISFX3/DAVIS346B/bias/PrSFBp/">
                            <attr key="coarseValue" type="byte">4</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">16</attr>
                            <attr key="sex" type="string">P</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="ReadoutBufBp" path="/1/1-DAVISFX3/DAVIS346B/bias/ReadoutBufBp/">
                            <attr key="coarseValue" type="byte">6</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">20</attr>
                            <attr key="sex" type="string">P</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="RefrBp" path="/1/1-DAVISFX3/DAVIS346B/bias/RefrBp/">
                            <attr key="coarseValue" type="byte">4</attr>
                            <attr key="currentLevel" type="string">Normal</attr>
                            <attr key="enabled" type="bool">true</attr>
                            <attr key="fineValue" type="short">50</attr>
                            <attr key="sex" type="string">P</attr>
                            <attr key="type" type="string">Normal</attr>
                        </node>
                        <node name="SSN" path="/1/1-DAVISFX3/DAVIS346B/bias/SSN/">
                            <attr key="operatingMode" type="string">ShiftedSource</attr>
                            <attr key="refValue" type="byte">1</attr>
                            <attr key="regValue" type="byte">33</attr>
                            <attr key="voltageLevel" type="string">SplitGate</attr>
                        </node>
                        <node name="SSP" path="/1/1-DAVISFX3/DAVIS346B/bias/SSP/">
                            <attr key="operatingMode" type="string">ShiftedSource</attr>
                            <attr key="refValue" type="byte">1</attr>
                            <attr key="regValue" type="byte">33</attr>
                            <attr key="voltageLevel" type="string">SplitGate</attr>
                        </node>
                    </node>
                    <node name="chip" path="/1/1-DAVISFX3/DAVIS346B/chip/">
                        <attr key="AERnArow" type="bool">false</attr>
                        <attr key="AnalogMux0" type="byte">0</attr>
                        <attr key="AnalogMux1" type="byte">0</attr>
                        <attr key="AnalogMux2" type="byte">0</attr>
                        <attr key="BiasMux0" type="byte">0</attr>
                        <attr key="DigitalMux0" type="byte">0</attr>
                        <attr key="DigitalMux1" type="byte">0</attr>
                        <attr key="DigitalMux2" type="byte">0</attr>
                        <attr key="DigitalMux3" type="byte">0</attr>
                        <attr key="ResetCalibNeuron" type="bool">true</attr>
                        <attr key="ResetTestPixel" type="bool">true</attr>
                        <attr key="SelectGrayCounter" type="bool">true</attr>
                        <attr key="TestADC" type="bool">false</attr>
                        <attr key="TypeNCalibNeuron" type="bool">false</attr>
                        <attr key="UseAOut" type="bool">false</attr>
                    </node>
                    <node name="dvs" path="/1/1-DAVISFX3/DAVIS346B/dvs/">
                        <attr key="AckDelayColumn" type="byte">0</attr>
                        <attr key="AckDelayRow" type="byte">4</attr>
                        <attr key="AckExtensionColumn" type="byte">0</attr>
                        <attr key="AckExtensionRow" type="byte">1</attr>
                        <attr key="ExternalAERControl" type="bool">false</attr>
                        <attr key="FilterBackgroundActivity" type="bool">true</attr>
                        <attr key="FilterBackgroundActivityDeltaTime" type="int">20000</attr>
                        <attr key="FilterPixel0Column" type="short">346</attr>
                        <attr key="FilterPixel0Row" type="short">260</attr>
                        <attr key="FilterPixel1Column" type="short">346</attr>
                        <attr key="FilterPixel1Row" type="short">260</attr>
                        <attr key="FilterPixel2Column" type="short">346</attr>
                        <attr key="FilterPixel2Row" type="short">260</attr>
                        <attr key="FilterPixel3Column" type="short">346</attr>
                        <attr key="FilterPixel3Row" type="short">260</attr>
                        <attr key="FilterPixel4Column" type="short">346</attr>
                        <attr key="FilterPixel4Row" type="short">260</attr>
                        <attr key="FilterPixel5Column" type="short">346</attr>
                        <attr key="FilterPixel5Row" type="short">260</attr>
                        <attr key="FilterPixel6Column" type="short">346</attr>
                        <attr key="FilterPixel6Row" type="short">260</attr>
                        <attr key="FilterPixel7Column" type="short">346</attr>
                        <attr key="FilterPixel7Row" type="short">260</attr>
                        <attr key="FilterRowOnlyEvents" type="bool">true</attr>
                        <attr key="Run" type="bool">true</attr>
                        <attr key="WaitOnTransferStall" type="bool">false</attr>
                    </node>
                    <node name="externalInput" path="/1/1-DAVISFX3/DAVIS346B/externalInput/">
                        <attr key="DetectFallingEdges" type="bool">false</attr>
                        <attr key="DetectFallingEdges1" type="bool">true</attr>
                        <attr key="DetectFallingEdges2" type="bool">true</attr>
                        <attr key="DetectPulseLength" type="int">120</attr>
                        <attr key="DetectPulseLength1" type="int">120</attr>
                        <attr key="DetectPulseLength2" type="int">120</attr>
                        <attr key="DetectPulsePolarity" type="bool">true</attr>
                        <attr key="DetectPulsePolarity1" type="bool">true</attr>
                        <attr key="DetectPulsePolarity2" type="bool">true</attr>
                        <attr key="DetectPulses" type="bool">false</attr>
                        <attr key="DetectPulses1" type="bool">false</attr>
                        <attr key="DetectPulses2" type="bool">false</attr>
                        <attr key="DetectRisingEdges" type="bool">false</attr>
                        <attr key="DetectRisingEdges1" type="bool">true</attr>
                        <attr key="DetectRisingEdges2" type="bool">true</attr>
                        <attr key="GenerateInjectOnFallingEdge" type="bool">true</attr>
                        <attr key="GenerateInjectOnRisingEdge" type="bool">true</attr>
                        <attr key="GeneratePulseInterval" type="int">1200000</attr>
                        <attr key="GeneratePulseLength" type="int">600000</attr>
                        <attr key="GeneratePulsePolarity" type="bool">false</attr>
                        <attr key="GenerateUseCustomSignal" type="bool">false</attr>
                        <attr key="RunDetector" type="bool">false</attr>
                        <attr key="RunDetector1" type="bool">true</attr>
                        <attr key="RunDetector2" type="bool">true</attr>
                        <attr key="RunGenerator" type="bool">true</attr>
                    </node>
                    <node name="imu" path="/1/1-DAVISFX3/DAVIS346B/imu/">
                        <attr key="AccelFullScale" type="byte">1</attr>
                        <attr key="AccelXStandby" type="bool">false</attr>
                        <attr key="AccelYStandby" type="bool">false</attr>
                        <attr key="AccelZStandby" type="bool">false</attr>
                        <attr key="DigitalLowPassFilter" type="byte">1</attr>
                        <attr key="GyroFullScale" type="byte">1</attr>
                        <attr key="GyroXStandby" type="bool">false</attr>
                        <attr key="GyroYStandby" type="bool">false</attr>
                        <attr key="GyroZStandby" type="bool">false</attr>
                        <attr key="LowPowerCycle" type="bool">false</attr>
                        <attr key="LowPowerWakeupFrequency" type="byte">1</attr>
                        <attr key="Run" type="bool">true</attr>
                        <attr key="SampleRateDivider" type="short">0</attr>
                        <attr key="TempStandby" type="bool">false</attr>
                    </node>
                    <node name="multiplexer" path="/1/1-DAVISFX3/DAVIS346B/multiplexer/">
                        <attr key="DropAPSOnTransferStall" type="bool">false</attr>
                        <attr key="DropDVSOnTransferStall" type="bool">true</attr>
                        <attr key="DropExtInputOnTransferStall" type="bool">true</attr>
                        <attr key="DropIMUOnTransferStall" type="bool">false</attr>
                        <attr key="ForceChipBiasEnable" type="bool">false</attr>
                        <attr key="Run" type="bool">true</attr>
                        <attr key="TimestampReset" type="bool">false</attr>
                        <attr key="TimestampRun" type="bool">true</attr>
                    </node>
                    <node name="usb" path="/1/1-DAVISFX3/DAVIS346B/usb/">
                        <attr key="BufferNumber" type="int">8</attr>
                        <attr key="BufferSize" type="int">8192</attr>
                        <attr key="EarlyPacketDelay" type="short">8</attr>
                        <attr key="Run" type="bool">true</attr>
                    </node>
                </node>
                <node name="system" path="/1/1-DAVISFX3/system/">
                    <attr key="DataExchangeBufferSize" type="int">64</attr>
                    <attr key="FramePacketMaxInterval" type="int">50000</attr>
                    <attr key="FramePacketMaxSize" type="int">4</attr>
                    <attr key="IMU6PacketMaxInterval" type="int">5000</attr>
                    <attr key="IMU6PacketMaxSize" type="int">8</attr>
                    <attr key="PacketContainerMaxInterval" type="int">5000</attr>
                    <attr key="PacketContainerMaxSize" type="int">4236</attr>
                    <attr key="PolarityPacketMaxInterval" type="int">5000</attr>
                    <attr key="PolarityPacketMaxSize" type="int">4096</attr>
                    <attr key="SpecialPacketMaxInterval" type="int">1000</attr>
                    <attr key="SpecialPacketMaxSize" type="int">128</attr>
                </node>
            </node>
            <node name="10-FileInput" path="/1/10-FileInput/">
                <attr key="autoRestart" type="bool">true</attr>
                <attr key="bufferSize" type="int">65536</attr>
                <attr key="filePath" type="string">/Users/federicocorradi/caer_out-test_file.aedat</attr>
                <attr key="keepPackets" type="bool">false</attr>
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="timeDelay" type="int">10000</attr>
                <attr key="timeSlice" type="int">10000</attr>
                <attr key="transferBufferSize" type="int">128</attr>
                <attr key="validOnly" type="bool">false</attr>
            </node>
            <node name="2-BAFilter" path="/1/2-BAFilter/">
                <attr key="deltaT" type="int">30000</attr>
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="subSampleBy" type="byte">0</attr>
            </node>
            <node name="3-Statistics" path="/1/3-Statistics/">
                <attr key="runAtStartup" type="bool">true</attr>
            </node>
            <node name="4-FrameEnhancer" path="/1/4-FrameEnhancer/">
                <attr key="contrastType" type="string">standard</attr>
                <attr key="demosaicType" type="string">standard</attr>
                <attr key="doContrast" type="bool">false</attr>
                <attr key="doDemosaic" type="bool">false</attr>
                <attr key="doWhiteBalance" type="bool">false</attr>
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="whiteBalanceType" type="string">standard</attr>
            </node>
            <node name="5-CameraCalibration" path="/1/5-CameraCalibration/">
                <attr key="aspectRatio" type="float">0</attr>
                <attr key="assumeZeroTangentialDistortion" type="bool">false</attr>
                <attr key="boardHeigth" type="int">5</attr>
                <attr key="boardSquareSize" type="float">29</attr>
                <attr key="boardWidth" type="int">9</attr>
                <attr key="calibrationPattern" type="string">chessboard</attr>
                <attr key="captureDelay" type="int">500000</attr>
                <attr key="doCalibration" type="bool">false</attr>
                <attr key="doUndistortion" type="bool">true</attr>
                <attr key="fitAllPixels" type="bool">false</attr>
                <attr key="fixPrincipalPointAtCenter" type="bool">false</attr>
                <attr key="loadFileName" type="string">camera_calib.xml</attr>
                <attr key="maxTotalError" type="float">0.3</attr>
                <attr key="minNumberOfPoints" type="int">20</attr>
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="saveFileName" type="string">camera_calib.xml</attr>
                <attr key="useFisheyeModel" type="bool">false</attr>
            </node>
            <node name="6-LaserPoseEstimation" path="/1/6-LaserPoseEstimation/">
                <attr key="captureDelay" type="int">500000</attr>
                <attr key="detectMarkers" type="bool">true</attr>
                <attr key="doSavetxt" type="bool">true</attr>
                <attr key="loadFileName" type="string">camera_calib.xml</attr>
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="saveFileName" type="string">3d_calib_points.txt</attr>
            </node>
            <node name="6-PoseEstimation" path="/1/6-PoseEstimation/">
                <attr key="captureDelay" type="int">50</attr>
                <attr key="detectMarkers" type="bool">true</attr>
                <attr key="doSavetxt" type="bool">false</attr>
                <attr key="loadFileName" type="string">camera_calib.xml</attr>
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="saveFileName" type="string">3d_calib_points.txt</attr>
            </node>
            <node name="60-VisualizerPolarity" path="/1/60-VisualizerPolarity/">
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="showStatistics" type="bool">false</attr>
                <attr key="subsampleRendering" type="int">1</attr>
                <attr key="zoomFactor" type="float">1.5</attr>
            </node>
            <node name="61-VisualizerFrame" path="/1/61-VisualizerFrame/">
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="showStatistics" type="bool">false</attr>
                <attr key="subsampleRendering" type="int">1</attr>
                <attr key="zoomFactor" type="float">1.5</attr>
            </node>
            <node name="62-VisualizerIMU6" path="/1/62-VisualizerIMU6/">
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="showStatistics" type="bool">false</attr>
                <attr key="subsampleRendering" type="int">1</attr>
                <attr key="zoomFactor" type="float">2</attr>
            </node>
            <node name="69-VisualizerLaser" path="/1/69-VisualizerLaser/">
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="showStatistics" type="bool">false</attr>
                <attr key="subsampleRendering" type="int">1</attr>
                <attr key="zoomFactor" type="float">2</attr>
            </node>
            <node name="69-VisualizerlaserLine" path="/1/69-VisualizerlaserLine/">
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="showStatistics" type="bool">false</attr>
                <attr key="subsampleRendering" type="int">1</attr>
                <attr key="zoomFactor" type="float">1</attr>
            </node>
            <node name="7-FileOutput" path="/1/7-FileOutput/">
                <attr key="bufferMaxInterval" type="int">20000</attr>
                <attr key="bufferSize" type="int">16384</attr>
                <attr key="directory" type="string">/Users/federicocorradi</attr>
                <attr key="keepPackets" type="bool">false</attr>
                <attr key="prefix" type="string">caer_out</attr>
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="transferBufferSize" type="int">128</attr>
                <attr key="validOnly" type="bool">false</attr>
            </node>
            <node name="7-LaserScanner" path="/1/7-LaserScanner/">
                <attr key="decayLaserTs" type="float">1.5</attr>
                <attr key="deltaT" type="int">15</attr>
                <attr key="doMeanFilter" type="bool">false</attr>
                <attr key="doSavetxt" type="bool">true</attr>
                <attr key="isLaserHorizontal" type="bool">true</attr>
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="saveFileName" type="string">2d_laser_points.txt</attr>
            </node>
            <node name="70-VisualizerPolarity" path="/1/70-VisualizerPolarity/">
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="showStatistics" type="bool">false</attr>
                <attr key="subsampleRendering" type="int">1</attr>
                <attr key="zoomFactor" type="float">1</attr>
            </node>
            <node name="71-VisualizerFrame" path="/1/71-VisualizerFrame/">
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="showStatistics" type="bool">false</attr>
                <attr key="subsampleRendering" type="int">1</attr>
                <attr key="zoomFactor" type="float">1</attr>
            </node>
            <node name="72-VisualizerIMU6" path="/1/72-VisualizerIMU6/">
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="showStatistics" type="bool">false</attr>
                <attr key="subsampleRendering" type="int">1</attr>
                <attr key="zoomFactor" type="float">1.5</attr>
            </node>
            <node name="9-FileOutput" path="/1/9-FileOutput/">
                <attr key="bufferMaxInterval" type="int">20000</attr>
                <attr key="bufferSize" type="int">16384</attr>
                <attr key="directory" type="string">/Users/federicocorradi/</attr>
                <attr key="keepPackets" type="bool">false</attr>
                <attr key="prefix" type="string">caer_out</attr>
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="transferBufferSize" type="int">128</attr>
                <attr key="validOnly" type="bool">false</attr>
            </node>
        </node>
        <node name="2" path="/2/">
            <node name="1-AmbergTrolley" path="/2/1-AmbergTrolley/">
                <attr key="doSaveTxt" type="bool">true</attr>
                <attr key="doSavetxt" type="bool">true</attr>
                <attr key="runAtStartup" type="bool">true</attr>
                <attr key="saveFileName" type="string">amberg_dump.txt</attr>
                <attr key="serialPort" type="string">/dev/tty.usbserial-1412A</attr>
            </node>
        </node>
        <node name="logger" path="/logger/">
            <attr key="logFile" type="string">/Users/federicocorradi/inilabs/caer_git/caer.log</attr>
            <attr key="logLevel" type="byte">5</attr>
        </node>
        <node name="server" path="/server/">
            <attr key="backlogSize" type="short">5</attr>
            <attr key="concurrentConnections" type="short">5</attr>
            <attr key="ipAddress" type="string">127.0.0.1</attr>
            <attr key="portNumber" type="int">4040</attr>
        </node>
    </node>
</sshs>

**Comment by llongi** [comment]
Config looks okay. But the error changed now, it's about an invalid header. Not sure what you got there, take a look with a hex-editor. I'll try to reproduce a few things here. Eventually send me the file or link it via GDrive or DropBox.

**Comment by federicohyo** [comment]
Hi Luca, this is not urgent. However the recordings are under GDrive->RailScanPrj->Data->LaserClassI_10062106->TakeI

this is reproducible under many machines... maybe something wrong at the header.

thank you for your help

**Comment by llongi** [comment]
Cannot reproduce. Just took a new recording now and played it back with no issues.
I'll try to find the time to look at the file in question more closely. Only thing I can think of given the message is the file being corrupted somehow, maybe something doing some newline conversion between the Unix and Windows formats...

**Comment by federicohyo** [comment]
Indeed, the input module is working fine (I just took a small recording and played it again). 
The recordings in gDrive are somehow corrupted, maybe when uploading them from my MacOsX.
Thanks Luca and sorry for the troubles. 

I am closing the issue.
