### ISSUE TITLE
Possible error in  caer/modules/fpgaspikegen/data/generate_input.py

### ISSUE THREAD

**Issue by sanfans** [inilabs/caer#111]
Problem at line 21:
address = (neuronAddress << 6) & 0xff | core_d & 0xf | (virtualSourceChip << 4) & 0x30
if neuronAddress is bigger than 3 (0011) the & 0xff brings all to 0...example with neuronAddress = 4 (0100)
01 0000 0000  & 00 1111 1111 ---> 00 0000 0000 (wrong)
replace & 0xff with & 0xffff

**Comment by federicohyo** [comment]
Thank you I have fixed it with the commit [https://github.com/inilabs/caer/commit/861fe34d6d8aabf29d786ed80909b4c3008c9c03]

address = ( (neuronAddress & 0xff) << 6) | core_d & 0xf | (virtualSourceChip << 4) & 0x30
