### ISSUE TITLE
chaining multiple modules that modify event stream = deadlock.

### ISSUE THREAD

**Issue by federicohyo** [inilabs/caer#117]
Using a configuration like the following seems to hang cAER. 

Both modules, "bafitler" and "filterspecial" modify the polarity events (i.e. readOnly = false). If the two modules are not chained, then everything seems to be working fine. When chained cAER hangs and does not show anything (seems like a deadlock).

       <node name="davisCamera" path="/davisCamera/">
            <attr key="autoRestart" type="bool">true</attr>
            <attr key="busNumber" type="short">0</attr>
            <attr key="devAddress" type="short">0</attr>
            <attr key="logLevel" type="byte">5</attr>
            <attr key="moduleId" type="short">1</attr>
            <attr key="moduleLibrary" type="string">caer_davis</attr>
            <attr key="runAtStartup" type="bool">true</attr>
            <attr key="serialNumber" type="string"/>
      </node>
        <node name="filterspecial" path="/filterspecial/">
            <attr key="deltaT" type="int">500</attr>
            <attr key="logLevel" type="byte">5</attr>
            <attr key="moduleId" type="short">12</attr>
            <attr key="moduleInput" type="string">1[0,1]</attr>
            <attr key="moduleLibrary" type="string">libpolarityfilterspecial</attr>
            <attr key="runAtStartup" type="bool">true</attr>
        </node>
        <node name="bafilter" path="/bafilter/">
            <attr key="deltaT" type="int">30000</attr>
            <attr key="logLevel" type="byte">5</attr>
            <attr key="moduleId" type="short">2</attr>
            <attr key="moduleInput" type="string">1[1a12]</attr>
            <attr key="moduleLibrary" type="string">caer_bafilter</attr>
            <attr key="runAtStartup" type="bool">true</attr>
            <attr key="subSampleBy" type="byte">0</attr>
        </node>

Here the gdb log:

federico@zfractal:/media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/caer$ gdb ./caer-bin 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./caer-bin...done.
(gdb) r
Starting program: /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/caer/caer-bin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2017-10-20 09:28:43 (TZ+0200): NOTICE: Logger: Initialization successful with log-level 5.
[New Thread 0x7fffeffa7700 (LWP 3921)]
2017-10-20 09:28:44 (TZ+0200): NOTICE: Mainloop: 12 modules found.

^C HERE PRESS CONTROL+C (AFTER LONG TIME WAITING)

Thread 1 "caer-bin" received signal SIGINT, Interrupt.
0x00000000005f8e2d in std::pair<decltype(nullptr), decltype(nullptr)>::pair<decltype(nullptr), decltype(nullptr), void>(decltype(nullptr)&&, decltype(nullptr)&&) (this=0x7fffffffcd30, __x=<unknown type in /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/caer/caer-bin, CU 0x140687, DIE 0x1bd884>, 
    __y=<unknown type in /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/caer/caer-bin, CU 0x140687, DIE 0x1bd889>)
    at /usr/include/c++/5/bits/stl_pair.h:145
145		: first(std::forward<_U1>(__x)), second(std::forward<_U2>(__y)) { }
(gdb) bt full
#0  0x00000000005f8e2d in std::pair<decltype(nullptr), decltype(nullptr)>::pair<decltype(nullptr), decltype(nullptr), void>(decltype(nullptr)&&, decltype(nullptr)&&) (this=0x7fffffffcd30, 
    __x=<unknown type in /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/caer/caer-bin, CU 0x140687, DIE 0x1bd884>, 
    __y=<unknown type in /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/caer/caer-bin, CU 0x140687, DIE 0x1bd889>)
    at /usr/include/c++/5/bits/stl_pair.h:145
No locals.
#1  0x00000000005f8e88 in std::make_pair<decltype(nullptr), decltype(nullptr)>(decltype(nullptr)&&, decltype(nullptr)&&) (
    __x=<unknown type in /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/caer/caer-bin, CU 0x140687, DIE 0x1bd931>, 
    __y=<unknown type in /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/caer/caer-bin, CU 0x140687, DIE 0x1bd936>)
    at /usr/include/c++/5/bits/stl_pair.h:281
No locals.
#2  0x00000000005ecd7f in IDExistsInDependencyTree (root=0xae6290, searchId=9, directionUp=false)
    at /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/caer/base/**mainloop.cpp:951**
No locals.
#3  0x00000000005ee034 in mergeActiveStreamDeps () at /media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/caer/base/mainloop.cpp:1192
        stream = @0xae53a0: {sourceId = 9, typeId = 9, isProcessor = true, users = std::vector of length 1, capacity 1 = {10}, 
          dependencies = std::shared_ptr (count 1, weak 0) 0xae5ea0}
        streamSourceId = 9
        originExists = {first = 0x0, second = 0x0}

**Comment by llongi** [comment]
Fixed in 5297ca7.
