### ISSUE TITLE
stopping and restarting the mainloop = segfault

### ISSUE THREAD

**Issue by federicohyo** [inilabs/caer#120]
To reproduce:

1) run cAER with the default configuration docs/davis-config.xml . "caer-bin -c /docs/davis-config.xml"
2) stop the mainloop by clicking on the GUI button
3) restart mainLoop
4) segmentation fault happens

here the log:

federico@zfractal:/media/federico/e247eb2e-273d-4a18-895a-6dd4c877d551/inilabs/caer$ ./caer-bin -c docs/davis-config.xml
2017-10-20 09:57:14 (TZ+0200): NOTICE: Logger: Initialization successful with log-level 5.
2017-10-20 09:57:14 (TZ+0200): NOTICE: Mainloop: 6 modules found.
Total events/second: 39 - Valid events/second: 39 Segmentation fault (core dumped)

**Comment by llongi** [comment]
Fixed in 5297ca77da7d93e20116afb0cea4004dbe66d2f2.
