### ISSUE TITLE
build error with option visualizer ...

### ISSUE THREAD

**Issue by Thanh-Binh** [inilabs/caer#122]
Problem: In the current version, the building with visualizer provides an error
"INT_MAX" is not found...

Proposed Solution: I have a look at the source code and found that we have to insert the following line
#include <climits>
into the header file "visualizer.hpp"

**Comment by federicohyo** [comment]
thank you, it has been fixed with commit 08df4b7d86aa2339d0302ca362e87c4ace36adc3
