### ISSUE TITLE
Dependencies state libcaer >= 2.4.0, which is not released

### ISSUE THREAD

**Issue by jo-m** [inilabs/caer#125]

**Comment by llongi** [comment]
Yes? Nothing new? Did something slip by me? What happened?

**Comment by llongi** [comment]
Ohh I see, sorry I thought you were talking about the dependencies *of* libcaer.
Yes, the development version of cAER depends on the development version of libcaer, nothing strange or noteworthy there. Releases always depend only on released versions, the dev-tree depends on whatever it needs.
