### ISSUE TITLE
Netparser code error

### ISSUE THREAD

**Issue by kimyo6835** [inilabs/caer#134]
Hi,

I just found small error in code.

In netparser.cpp line 71:
sshsNodeCreateBool(moduleData->moduleNode**, "ClearNetwork",** false, SSHS_FLAGS_NORMAL, "def");

In netparser.cpp line 99:
state->clear = sshsNodeGetBool(moduleData->moduleNode, # **"Clear Network"**)

There is a space between Clear and Network in line 99, which caused error when I tried to add module.

**Comment by federicohyo** [comment]
fixe in commit ce259cb
