### ISSUE TITLE
Creating AEDAT.

### ISSUE THREAD

**Issue by krebsm249** [inilabs/caer#145]
Hello, I don't have any experience with C or working with the DAVIS240C. I was able to get libcaer and caer installed on a jetson tx2. I also was able to get the libcaer examples built. Is there a simple way, or example, that will create the AEDAT file? Sorry for the dumb question, just very new at this. Thanks

**Comment by llongi** [comment]
Hi, I've committed an example under docs/davis-record-file.xml. You can use that as a configuration file for cAER to have it write the events coming from a DAVIS camera to a file (be sure to edit the 'directory' parameter to match your system).
