### ISSUE TITLE
APS Video for external application?

### ISSUE THREAD

**Issue by Thanh-Binh** [inilabs/caer#16]
I have some questions:
how can I ask cAER 
1. if a APS video data at a time instance is available for capturing into the application?
2. if it is available, I can get those data.?

do you have any mechanismus for avoiding read from and write to the same data (e.g. video data for APS and ) at the same time?

**Comment by llongi** [comment]
I'm not exactly sure what you mean here. Do you mean writing an AVI made up of the APS frames? That could be done using [OpenCV's VideoWriter](http://docs.opencv.org/3.0-alpha/modules/videoio/doc/reading_and_writing_video.html#videowriter) for example. Or any other C library that can write videos out of raw frames, which is what APS frames are in the end.

**Comment by Thanh-Binh** [comment]
No, I do not mean VideoWriter.
I mean APS video should be sent anyhow into application.
I think, using unix socket for sending video data to application maybe the best way.

**Comment by llongi** [comment]
Yes, I agree that to exchange data locally between cAER and some other process, a local Unix socket is the easiest and most performant way. There is a discussion about it here:
https://sourceforge.net/p/jaer/discussion/631958/thread/cbdfb9af/
Closing this ticket then.
