### ISSUE TITLE
File input: does not require the libpng dependency

### ISSUE THREAD

**Issue by breznak** [inilabs/caer#20]
Or so it seems to me (?) 

`libpng>=1.6` should not be forced for "input" type of file I/O. 

PS: I'm bothering about that is libpng(-dev)>=1.6 seems not to be available easily (ppa) on Ubuntu 16.04 LTS.

**Comment by llongi** [comment]
Now the libpng dependency is optional, as it was always intended to be. If found, then PNG compression support is enabled for both input and output (if they are enabled themselves). Thanks for the report!
