### ISSUE TITLE
Input file: fail to parse oldest .dat format with no header

### ISSUE THREAD

**Issue by breznak** [inilabs/caer#22]
example files are yours on the web, eg. `Tmpdiff*-patrick juggling.dat`, 
these files have no textual header, only binary. 

```
ERROR: 10-FileInput: Failed to parse header.
```

RelatedL #19

**Comment by llongi** [comment]
Hmm those are very early AEDAT 1.0 format files. They are there as quick examples for jAER.
In cAER I really don't ever want to support AEDAT 1.0, if you really depend on opening one of those super old files in cAER, just use jAER to re-log it into AEDAT 2.0 format at least, which will be supported soon by cAER. I've added a slightly more informative error message in revision 152406cd26baabdba9e9b27172f59d071da22b19.
