### ISSUE TITLE
Release number for libcaer

### ISSUE THREAD

**Issue by aicioara** [inilabs/caer#4]
The prerequisite for caer is `libcaer >= 2.0.0`, but the latest tag [here](https://github.com/inilabs/libcaer/releases) is 1.0.3

**Comment by llongi** [comment]
Yes, current caer master/HEAD tracks libcaer master/HEAD, so we use features that only the unreleased version 2.0.0 of libcaer has. caer tag/0.9.9 is still compatible with libcaer 1.0.3. I'd urge you to just use both HEAD versions to get all the newest features and bug-fixes.

**Comment by aicioara** [comment]
Thank you for the answer. My point was that the description is misleading. Stable release numbers should be bumped.
