### ISSUE TITLE
mac os x : caer does not compile,  prctl() is not supported

### ISSUE THREAD

**Issue by federicohyo** [inilabs/caer#5]
Here is the log:

make[2]: *** [utils/caerctl/CMakeFiles/caer-ctl.dir/__/__/ext/sshs/sshs_helper.c.o] Error 1
make[1]: *** [utils/caerctl/CMakeFiles/caer-ctl.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 11%] Building C object CMakeFiles/caer-bin.dir/base/config.c.o
[ 13%] Building C object CMakeFiles/caer-bin.dir/base/config_server.c.o
In file included from /Users/federicocorradi/inilabs/caer_git/base/config_server.c:11:
/Users/federicocorradi/inilabs/caer_git/ext/c11threads_posix.h:8:10: fatal error: 'sys/prctl.h' file not found
#include <sys/prctl.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/caer-bin.dir/base/config_server.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
3 warnings generated.
make[1]: *** [CMakeFiles/caer-bin.dir/all] Error 2
3 warnings generated.
[ 16%] Linking C executable udpststat
[ 19%] Linking C executable tcpststat
[ 19%] Built target tcpststat
[ 19%] Built target udpststat
make: *** [all] Error 2

and here a stackoverflow explanation to it: http://stackoverflow.com/questions/13617693/how-can-i-install-linux-sys-prctl-h-to-lion, it seems that prctl() is not supported in many Unix system like Mac Os X. Can we have a switch to this functionality?

**Comment by llongi** [comment]
Fixed in commit cc395de1d39d45728037fd0e4a5535c81c1d6346.
