### ISSUE TITLE
recording data with davis640?

### ISSUE THREAD

**Issue by Thanh-Binh** [inilabs/caer#52]
Currently, I use the following option for recording data:
cmake -DDAVISFX3=1 -DENABLE_FILE_OUTPUT=1 -DENABLE_BAFILTER=1 -DENABLE_VISUALIZER=1 . && make -j8 

and my caer-config.xml the path is set to "/home/binh/Neuromorphics/data"

But I really do not find out any aedat file in this folder.
Do anybody know where is that problem?
Thanks.

**Comment by llongi** [comment]
This should work. Did you try removing the CMake cache like Federico suggested in the other ticket?

**Comment by Thanh-Binh** [comment]
it works now so I will close this issue, best thank
