### ISSUE TITLE
working with median tracker?

### ISSUE THREAD

**Issue by Thanh-Binh** [inilabs/caer#53]
I am interested in testing median tracker, but really do not know if the results (black box of the detected object) can be visualized? 
Thanks

**Comment by federicohyo** [comment]
Hi Bihn,

yes, the median tracker automatically opens a visualizer that shows a bounding box.

see the following picture:

![median_tracker](https://cloud.githubusercontent.com/assets/7521438/24102485/70335b7a-0d7c-11e7-86c5-0fa5f6bd8b1d.png)

I compiled cAER with
$ cmake  -DDVS128=1 -DDAVISFX3=0 -DDAVISFX2=0 -DENABLE_STATISTICS=1 -DENABLE_BAFILTER=1 -DENABLE_VISUALIZER=1 -DENABLE_MEDIANTRACKER=1  .
