### ISSUE TITLE
flash hardware FX3

### ISSUE THREAD

**Issue by Thanh-Binh** [inilabs/caer#55]
In the current version, my DAVIS640 can not be detected by CAER, because HW version is too old.
I use flashy now for upgrading it, but in the tab "device specific", it need to select:
FX3 firmware file
FPGA logic file
Serial number etc
Where can I get those info?

**Comment by llongi** [comment]
Serial number and the rest doesn't have to be updated.
Only FX3 firmware file and FPGA logic.
You can get the right files for your device from the table at:
https://inilabs.com/support/software/reflashing/#h.v8v6if5e2ell

**Comment by Thanh-Binh** [comment]
Best thank
