### ISSUE TITLE
Any document about the new filter?

### ISSUE THREAD

**Issue by Thanh-Binh** [inilabs/caer#65]
do you have any document or any information / hint about the effect of the new filters like Denoisy AutoEncoder, Gesture learning filter, learning filter, meanrate filter etc.?

How can I get the results/outputs of each filter?
Thanks

**Comment by federicohyo** [comment]
Hi Binh,

unfortunately these new filters are highly experimentals and will not be supported by us in the next caer release (that will be in about a week). However, they might get supported in the upcoming months. In addition, these filters are used in conjuction with the Dynap-se neuromorphic processor and without such a processor you will not able to run them.

with best regards,
 Federico

**Comment by Thanh-Binh** [comment]
thanks

**Comment by Thanh-Binh** [comment]
@federicohyo @llongi do you have any filter for filtering events generated by camera motion?
