### ISSUE TITLE
Warning: FileInput: Failed to raise thread priority for Input Assembler thread

### ISSUE THREAD

**Issue by breznak** [inilabs/caer#69]
`2017-04-21 23:23:55 (TZ+0200): INFO: 10-FileInput: Failed to raise thread priority for Input Assembler thread. You may experience lags and delays.`

I get this on linux, compiled with `FILE_INPUT=1`, `NETWORK_OUTPUT=1`

**Comment by llongi** [comment]
This is normal, indeed it is only an informative message to tell you what's happening.
On Linux, not anybody can raise the priority of a thread/process, it depends on the ulimit configuration and/or other system settings.
