### ISSUE TITLE
branch modules failed to compile

### ISSUE THREAD

**Issue by federicohyo** [inilabs/caer#78]
I'm using the following cmake configuration

cmake -DDAVISFX3=1 -DDVS128=1 -DDAVISFX2=1 -DSTATISTICS=1 -DBAFILTER=1 -DVISUALIZER=1 .

the error I get is about libuv...
config_server.cpp:12:2: error: ‘uv_async_t’ does not name a type uv_async_t asyncShutdown;
config_server.cpp:16:36: error: variable or field ‘configServerConnection’ declared void static void configServerConnection(uv_stream_t *server, int status);
                                   
which version is required? I have libuv1-dev from ubuntu16.04 repo.. what am I missing?

thank you!

**Comment by llongi** [comment]
Currently work in progress, it's normal that it's broken.

**Comment by llongi** [comment]
Compiles fine again, config-server now uses Boost.ASIO.
