### ISSUE TITLE
Add growing size/unlimited EventPacket implementation

### ISSUE THREAD

**Issue by breznak** [inilabs/caer#8]
to allow event packets that would not have the `max event size` (=will be unlimited). 

See https://github.com/inilabs/caer/pull/2#discussion_r65050145 for details.

**Comment by llongi** [comment]
Event Packet growing implemented in inilabs/libcaer@1524f13579b7cf49f34a9cda4b2bbcf3f69b0805.

**Comment by breznak** [comment]
https://github.com/inilabs/libcaer/commit/1524f13579b7cf49f34a9cda4b2bbcf3f69b0805#diff-35cb11a75a21235bd583384bcd552036R380 

If I understand this, there is still a `max` parameter, would it be possible/useful to implement a packet as a growing array (vector), completely w/o any `maxSize` param? (internally using the grow method..)
