### ISSUE TITLE
linker command failed

### ISSUE THREAD

**Issue by NatINI** [inilabs/caer#80]
Hi,

I just pulled caer and libcaer and the following error message appeared:

clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any idea on this?

Cheers
Nat

**Comment by llongi** [comment]
What are you doing when you get that error message? Did you execute cmake as described in the README before doing make? Did you install libcaer before trying to compile caer?

**Comment by NatINI** [comment]
Yes I did all of this before getting that error message. I basically pulled
in order to get the poisson spike generator updated. Never saw that message
before.

**Comment by llongi** [comment]
Try cleaning up the cmake temporary files:
`rm -Rf CMakeFiles/ CMakeCache.txt`
and then execute cmake + make again.

**Comment by llongi** [comment]
Closing.
