### ISSUE TITLE
A default caer-config.xml?

### ISSUE THREAD

**Issue by Thanh-Binh** [inilabs/caer#85]
It is very nice for user to have a default config file from developers because we do not have any overview about which parameters are valid and can be changed?
Thanks

**Comment by llongi** [comment]
With the newly merged modules system in master, there now is docs/davis-config.xml and docs/dynapse-config.xml to start with. By default cAER generates an empty config file, and when you add modules to it they add their own configuration parameters, so if they exist they are valid. Further if a parameter is now removed from a module, it will not save it again to the XML file at the end of the run, so you don't get "stale" parameters hanging around.

**Comment by Thanh-Binh** [comment]
Thanks for your explain
